from .api import api_function
from .types import *
from typing import List, Mapping

create_tournament_code = api_function('/lol/tournament-stub/v4/codes', List[str], count=int, tournamentId=int)
get_all_champion_masteries = api_function('/lol/champion-mastery/v4/champion-masteries/by-summoner/{}', List[ChampionMastery], str)
get_by_account_id = api_function('/lol/summoner/v4/summoners/by-account/{}', Summoner, str)
get_by_puuid = api_function('/lol/summoner/v4/summoners/by-puuid/{}', Summoner, str)
get_by_summoner_id = api_function('/lol/summoner/v4/summoners/{}', Summoner, str)
get_by_summoner_name = api_function('/lol/summoner/v4/summoners/by-name/{}', Summoner, str)
get_challenger_league = api_function('/lol/league/v4/challengerleagues/by-queue/{}', LeagueList, str)
get_champion_info = api_function('/lol/platform/v3/champion-rotations', ChampionInfo)
get_champion_mastery = api_function('/lol/champion-mastery/v4/champion-masteries/by-summoner/{}/by-champion/{}', ChampionMastery, int, str)
get_champion_mastery_score = api_function('/lol/champion-mastery/v4/scores/by-summoner/{}', int, str)
get_current_game_info_by_summoner = api_function('/lol/spectator/v4/active-games/by-summoner/{}', CurrentGameInfo, str)
get_featured_games = api_function('/lol/spectator/v4/featured-games', FeaturedGames)
get_grandmaster_league = api_function('/lol/league/v4/grandmasterleagues/by-queue/{}', LeagueList, str)
get_league_by_id = api_function('/lol/league/v4/leagues/{}', LeagueList, str)
get_league_entries = api_function('/lol/league/v4/entries/{}/{}/{}', List[LeagueEntry], str, str, str, page=int)
get_league_entries_for_summoner = api_function('/lol/league/v4/entries/by-summoner/{}', List[LeagueEntry], str)
get_lobby_events_by_code = api_function('/lol/tournament-stub/v4/lobby-events/by-code/{}', LobbyEventWrapper, str)
get_master_league = api_function('/lol/league/v4/masterleagues/by-queue/{}', LeagueList, str)
get_match = api_function('/lol/match/v4/matches/{}', Match, int)
get_match_by_tournament_code = api_function('/lol/match/v4/matches/{}/by-tournament-code/{}', Match, str, int)
get_match_ids_by_tournament_code = api_function('/lol/match/v4/matches/by-tournament-code/{}/ids', List[int], str)
get_match_timeline = api_function('/lol/match/v4/timelines/by-match/{}', MatchTimeline, int)
get_matchlist = api_function('/lol/match/v4/matchlists/by-account/{}', Matchlist, str, champion=List[int], queue=List[int], season=List[int], endTime=int, beginTime=int, endIndex=int, beginIndex=int)
get_shard_data = api_function('/lol/status/v3/shard-data', ShardStatus)
get_third_party_code_by_summoner_id = api_function('/lol/platform/v4/third-party-code/by-summoner/{}', str, str)
register_provider_data = api_function('/lol/tournament-stub/v4/providers', int)
register_tournament = api_function('/lol/tournament-stub/v4/tournaments', int)
